const products = [
    {   _id: '1',
    name: 'Airpod wireless ',
    image: '/images/airpods.jpg',
    description: 
        'Blue tooth technology that gives you the sound you can only imagine but is now in your hands for great use',
    brand: 'Apple',
    category: 'Electronics',
    price: '20 000',
    countInStock: 3,
    rating: 4,
    numberReviews: 4,
},
{   _id: '2',
    name: 'Alexa Music Ap101',
    image: '/images/alexa.jpg',
    description: 
        'Listen o the future and do the past with a button at your reach',
    brand: 'Apple',
    category: 'Electronics',
    price: '15 000',
    countInStock: 0,
    rating: 4.5,
    numberReviews: 15,
},
{   _id: '3',
    name: 'Camon Camera XD6',
    image: '/images/camera.jpg',
    description: 
        'See with clearity and super ',
    brand: 'Camon',
    category: 'Electronics',
    price: '245 250',
    countInStock: 10,
    rating: 3.5,
    numberReviews: 5,
},
{   _id: '4',
    name: 'mouse',
    image: '/images/mouse.jpg',
    description: 
        'Click! click is the sound that takes you around the world within seconds',
    brand: 'Micro Soft',
    category: 'Technology',
    price: '1500',
    countInStock: 50,
    rating: 2,
    numberReviews: 20,
},
{   _id: '5',
    name: 'X10 Iphone Technologies',
    image: '/images/phone.jpg',
    description: 
        'A button away from you is your family abraod',
    brand: 'Apple',
    category: 'Phones',
    price: '350 500',
    countInStock: 12,
    rating: 3,
    numberReviews: 20,
},
{   _id: '6',
    name: 'Play Station 2021',
    image: '/images/playstation.jpg',
    description: 
        'Be in the game right from the comfort of your house',
    brand: 'Amazon',
    category: 'Games',  
    price: '120 250',
    countInStock: 15,
    rating: 5,
    numberReviews: 200,
}
]

export default products